#!/usr/bin/env fish

. ~/.fish/config.fish.1-functions.fish

set FLY_API_TOKEN "$(cat ~/.fly/config.yml | yq .access_token)"

show_cmd docker build . -t llmsafe \
    --build-arg GH_TOKEN="$GH_TOKEN" \
    --build-arg FLY_API_TOKEN="$FLY_API_TOKEN"
