#!/usr/bin/env fish

# To use a persistent machine
# orb run bash $argv

# To use a one-shot docker run
docker run \
  --rm \
  -v /tmp:/tmp \
  -v "$PWD":"$PWD":ro \
  -v "$HOME/.gitconfig":"/root/.gitconfig":ro \
  -v "$HOME/.gitignore":"/root/.gitignore":ro \
  -w "$PWD" \
  $DOCKER_OPTS \
  llmsafe \
  /bin/bash \
  $argv
